title: Jörmungandr - the Snake Game
description: A modern Snake Game

# custom supported theme
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme 

show_downloads: true

github:
  zip_url: http://example.com/download.zip
